### ISSUE TITLE
Is autoNumeric works on Oracle Apex?

### ISSUE THREAD

**Issue by mathiasmaciel97** [autoNumeric/autoNumeric#600] opened 2018-08-25 14:08 UTC
I tried to use it by setting all properties like the old version is installed <**_@version: 1.9.43 - 2015-12-19 GMT 4:00 PM / 16:00_**> on my Oracle Apex. Actually all works fine until I try to submit the page even setting the property **unformatOnSubmit**. When this event occurs I got an error of format mask that's why I'm trying to use that property. To give you an idea of the basic default configuration that I made here's the link of the [post](http://apexbyg.blogspot.com/2017/04/auto-format-number-items-in-apex.html) mentioning the use of this plugin on Oracle Apex. Hope you can help me.

**Comment by AlexandreBonneau** [comment] 2018-08-27 11:07
No users mentioned Oracle Apex before, and from what I'm seeing it seems you can add custom JS to it, so AutoNumeric should work since it has no dependencies.

In the link you posted, the author uses `v2.0.13`. Have you tried that?

**Comment by mathiasmaciel97** [comment] 2018-08-27 14:20
I tried the last version but doesn't work. I don't know if the version you're mentioning has the property **unformatOnSubmit**.

**Comment by AlexandreBonneau** [comment] 2018-08-28 07:52
Thanks for reporting this issue, however with the few information you gave us, we are not able to correctly reproduce it.
Could you please create a [reproducible test case](https://codepen.io/pen/) so we can fix your bug?

**Comment by mathiasmaciel97** [comment] 2018-09-22 14:15
Hi there,
The best way you can get a reproducible case and also see how it works in apex is look at the post I that attach in the pull request. Few days ago I tried by using the last version but still not working.

**Comment by AlexandreBonneau** [comment] 2018-09-27 20:00
Which pull request are you referring to? I cannot find any from you.

**Comment by mathiasmaciel97** [comment] 2018-09-28 11:05
Don’t worry, I fixed it by using v2.0.13. There's also a quick question but I don’t know is you’re open to answer. Anyway, thanks for your patience.

**Comment by AlexandreBonneau** [comment] 2018-09-28 18:50
I'm not sure to follow.

Can we close this issue?
Does using the latest version (`v4.4.3` as of today) also 'fix' your problem? (You cannot live in the past!)

**Comment by mathiasmaciel97** [comment] 2018-09-28 19:30
Yes close it. I can prove that only with that version it works perfectly.
No, using the latest version no works. When page loads I inspect and it load with error saying like: AutoNumeric.js it not a function.

**Comment by AlexandreBonneau** [comment] 2018-09-28 19:39
This is likely because you are probably not initializing the AutoNumeric objects with the [*new* format](https://github.com/autoNumeric/autoNumeric/#initialization).

Meanwhile, I'm closing this issue since you've found a workaround.

**Closed by AlexandreBonneau** 2018-09-28 19:39 UTC
Labels: :tipping_hand_man: Need reporter feedback
