### ISSUE TITLE
Problem when trying to insert a number with a dot.

### ISSUE THREAD

**Issue by Landead** [autoNumeric/autoNumeric#460] opened 2017-06-21 08:59 UTC
### Expected behavior
When i paste number with dot like this: 12.34, i want see: 12,34 (replace on dot on comma)

### Actual behavior
When i paste number with dot like this: 12.34, i get this: 1 234,00 (ignore dot)

### Steps to reproduce the problem
1. Using autoNumeric `<v2.0.0>` and the browser `Chrome` version `58.0.3029.110 (64-bit)` on `Windows 10 64 bit`,
2. I used the options const autoNumericOptionsEuro = {
    digitGroupSeparator        : ' ',
    decimalCharacter           : ',',
    decimalCharacterAlternative: '.',
    roundingMethod             : 'U'
};
3. Initialized my AutoNumeric object with the call $(".numericInput").autoNumeric('init', autoNumericOptionsEuro);

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
https://jsfiddle.net/6t5fgpug/2/

I fix this proble like this
https://jsfiddle.net/6t5fgpug/3/
but is bad solution i think, because it not work with dot GroupSeparator

**Comment by AlexandreBonneau** [comment] 2017-06-21 22:33
Hey Daniil, thanks for taking the time to report this.

Unfortunately, this is currently the expected behavior ; this is a duplicate of #424, which detail why this happens (and this has been mentioned in #426 as well).

A PR is needed to change this behavior though, so in time this will get fixed!

**Closed by AlexandreBonneau** 2017-06-21 22:33 UTC
