### ISSUE TITLE
Entering the `decimalCharacterAlternative` is not taken into account on Android Chrome

### ISSUE THREAD

**Issue by balek** [autoNumeric/autoNumeric#264] opened 2016-11-16 10:45 UTC
I've tried to set aDec to `.` and altDec to `,` and vice versa. In both combinations altDec doesn't work. Just Chrome is affected, everything is working fine on Android Browser.

**Comment by BobKnothe** [comment] 2016-11-16 12:02
The issue is with the Android Chrome and their decision to not support the "keypress" event and character codes which is critical to how autoNumeric functions. 

I (we) are in the initial sets of finding a work around using the "input" event. This may take some time to write and test.

Please be patient.

**Comment by AlexandreBonneau** [comment] 2016-11-17 09:24
This issue being a duplicate of #206, please consider closing this one and updating the initial one.

**Comment by AlexandreBonneau** [comment] 2016-12-24 12:29
Using Chrome 55.0.2883.91 under Android, I do experience the `altDec` problem.
Also, issue #206 is different from this one.

**Comment by AlexandreBonneau** [comment] 2017-04-07 07:42
This is fixed by @BobKnothe work in this [commit](https://github.com/autoNumeric/autoNumeric/commit/5257865155c6e75a8a6f51fbe69ae2ab946a132c). 🎉

**Closed by AlexandreBonneau** 2017-04-07 07:42 UTC
Labels: Bug, Mobile, On hold
