### ISSUE TITLE
Input is duplicated and reversed on devices with Android < 7.0

### ISSUE THREAD

**Issue by JoHauns** [autoNumeric/autoNumeric#522] opened 2017-10-25 13:26 UTC
### Expected behavior
Entering `123` should format the input to `123 €`

### Actual behavior
Entering `123` resulted in `123.321 €` on SAMSUNG GALAXY S5 (Android 6.0.1, Chrome v61)
Entering `123` resulted in `12.321 €` on HTC ONE (Android 5.0.2, Chrome v61)

### Steps to reproduce the problem
1. I tested this using autoNumeric `v4.1.0`and the browser `Chrome` version `61` on `Android 6.0.1` and `Android 5.0.2`,
2. I used the example from http://autonumeric.org 

I've had no problems with autoNumeric on devices using Android > v7.0. 

Best regards,
J.

**Comment by danielmuehlbacher** [comment] 2017-11-07 14:54
Hi there,

is there any forecast when this bug will be handled? This one makes the whole plugin unusable on a lot of devices. Thanks a lot!

Best regards,
Daniel

**Comment by AlexandreBonneau** [comment] 2017-11-07 18:24
This one will be hard for me to fix since I do not own an Android <7 device, and globally Android is a pain to support (due to the non-existent `key` info on that platform).

@BobKnothe Would you have such device for the tests?

It's likely we would need a pull request from a user that can test his fix, sorry.

**Comment by danielmuehlbacher** [comment] 2017-11-08 10:10
Maybe you can test it with https://www.browserstack.com? It's free for open source projects...

**Comment by AlexandreBonneau** [comment] 2017-11-08 10:29
Ideally yes @danielmuehlbacher, I got an account there since last April, but failed to find the time to set it up correctly (cf. issue #435).
If you already used that before, perhaps you could help us with this one?
That would be great!

**Comment by danielmuehlbacher** [comment] 2017-11-08 11:05
Sorry, i didn't used it before (we're not developing open source). But we ordered a Android 6 device today and will have a look at it.

**Comment by JanThiel** [comment] 2017-11-16 08:39
Hi @danielmuehlbacher We currently faced the same issue but were finally able to pinpoint the source of it and why it only happens with Samsung Devices.

The issue is caused by the Samsung Keyboard Autocorrect Feature ("Text suggestions"). Credits to this finding goes to the Angular Community: https://github.com/assisrafael/angular-input-masks/issues/104

If you disable this Samsung Feature, the autoNumeric works as expected. As a more clean workaround (which does not require user interaction to globally disable the feature) it works, if you add this to the <input> field which uses autoNumeric:

```autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"```

This disables the Samsung autocomplete feature.

No chance for a beauty award, but a reliable solution...

Best Regards,

Jan

**Comment by danielmuehlbacher** [comment] 2017-11-16 09:43
Hi @JanThiel ,

thank you very much! We ordered a no-name Smartphone with stock Android 6.0 and could *not* reproduce the problem... The fact it's a Samsung (and i guess HTC) issue explains that :)

Now we have a Samsung Galaxy S5 test-device and will your try your solution. Thanks a lot!

Best regards,
Daniel

**Comment by AlexandreBonneau** [comment] 2017-11-16 20:28
Thanks for the workaround @JanThiel !

Since according to this link this affects only a specific subset of old Samsung devices (that we do not own), anybody hereowning such a device willing to tinker AutoNumeric to see if a permanent fix could be implemented? :)

**Comment by JanThiel** [comment] 2017-11-16 20:34
@AlexandreBonneau That is sadly a wrong assumption of that Thread. We have a broad set of Samsung devices available for testing and can reproduce the issue up to the Galaxy S8. So this is a major and relevant issue for many people.

You should be able to add the required attributes to the input field if the user agent states android within the init code. As this is quite straight forward, I don't see any risks in this. The only downside is loosing autocomplete for these fields which is better than losing the whole input ;-)

Jan

**Comment by AlexandreBonneau** [comment] 2017-11-17 09:18
I do not like the sound of relying on the *user agent* to check for anything on the client, however as you said, the downside of not being able to *use* the input correctly is pretty heavy.

I'll see what I can do when I get back from vacation at the end of next week!

**Comment by JanThiel** [comment] 2017-11-17 09:29
Personally I also dislike UA sniffing. Suggesting it is based on the "Why should hacks target anything else than where they are really required?" paradigma. I do not see any bad in generally adding this attributes. But you never know who uses your code in which way... Just to keep the impact as small as possible.

Have a great vacation!

**Comment by nvanrooij** [comment] 2017-12-11 12:58
I have a Samsung Galaxy Tab A 10.1 tablet which has the same problem, but autocomplete is not turned off by using the properties Jan Thiel suggested. If you need me to test something please let me know.

**Comment by AlexandreBonneau** [comment] 2017-12-12 07:02
@nvanrooij on your end, when you are using the `autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"` workaround, the bug is still shown?

**Comment by nvanrooij** [comment] 2017-12-13 13:33
That is correct @AlexandreBonneau. I have tested this in Chrome and Samsung browser. I am running Android 7.0.

The plot thickens though. When checking my system settings I found out that I do not have predictive text enabled. The only options I have enabled for the Samsung keyboard are: spelling-control, automatic capitalization, automatic spacing. Even when I turn all these options off I still experience the bug. I then installed two different keyboards (Google Gboard, Swiftkey) to see if that solves the problem, but I still experience the bug with those keyboards.  Only when I change the input type to 'phone' the bug goes away.

Is there another 'autocomplete' setting in Android that I should change?

**Comment by AlexandreBonneau** [comment] 2017-12-14 07:17
@nvanrooij I'm not an Android expert so I couldn't say.

This is bad news since apparently the workaround from @JanThiel isn't 100% functional :/
It also mean we cannot rely on it to fix that bug, unless somebody manages to narrow the problem down.
Otherwise I envision an added complexity to the `input` event handler to manage this specific case and that cannot be good..

**Comment by alexturpin** [comment] 2018-01-05 01:53
Just as an update, we just encountered this on our end and it's happening on various customer devices as well as my own Google Pixel (not a Samsung device). Setting `autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"` does not seem to help either.

**Comment by AlexandreBonneau** [comment] 2018-01-28 12:01
Hey guys, I've created a potential fix for this.
Anybody here could try is on their Android device?

Here is the [minified AutoNumeric library](https://gist.github.com/AlexandreBonneau/5c21570e29d7830302efcc968730368b).

Thanks!

**Comment by nvanrooij** [comment] 2018-01-29 08:19
I have tested this on a Samsung Galaxy TAB A 10.1 2016 with Android 7.0. This has fixed the problem where the input is scrambled (yay!), but the value is cleared once I select a different form input. This only happens on my android device, not on PC or iPhone.

**Comment by AlexandreBonneau** [comment] 2018-01-29 10:19
Thanks for your testing @nvanrooij !

Would it be possible to check that [codepen](https://codepen.io/AnotherLinuxUser/pen/VQwemG?editors=1111) with your Android 7.0 device?

This will allow us to see how (or even if) the raw value is modified whenever you entered numbers in that text field.

**Comment by nvanrooij** [comment] 2018-01-29 10:28
I just tested the codepen, but nothing is happening in the console on my Android device. On my PC I can see the value changing.

**Comment by alexturpin** [comment] 2018-01-29 15:43
@AlexandreBonneau that fix solves the issue for me on my Pixel! Awesome work!

**Comment by AlexandreBonneau** [comment] 2018-01-29 19:14
@alexturpin I'm glad to hear it :)

@nvanrooij this is annoying ;x
Could you please check that [updated codepen](https://codepen.io/AnotherLinuxUser/pen/jZOzZR?editors=0011) and paste here the event orders as shown in the console?
I'm particularly interested in seeing how the `composition*` events are sent on this Android version.
Thanks!

**Comment by nvanrooij** [comment] 2018-01-31 08:10
Once I type something I only get the line: "Log Skipped: Sorry, this log was too large for console. You might need to use the browser console instead." 3 times per keystroke. Tested in Samsung and Chrome browser.

**Comment by AlexandreBonneau** [comment] 2018-01-31 09:49
@nvanrooij yes, you would need to open the console from your browser, if that's even possible on mobile.

**Comment by nvanrooij** [comment] 2018-01-31 14:36
@AlexandreBonneau This should be possible (https://developers.google.com/web/tools/chrome-devtools/remote-debugging/), but I won't be able to try this until tomorrow or friday.

**Comment by AlexandreBonneau** [comment] 2018-02-07 23:58
@nvanrooij any chance that you were able to test it out?

**Comment by alexturpin** [comment] 2018-02-08 03:27
@AlexandreBonneau Can I help get the info you need even if the newest example works for me?

**Comment by AlexandreBonneau** [comment] 2018-02-08 06:26
Thanks you @alexturpin for proposing, but while it seems my patch fixed that current issue, it seems it has some side effects on some Android version as per @nvanrooij comment:
> the value is cleared once I select a different form input

So since I cannot reproduce that bug myself, I need as much info as possible on what could happen there. Running the [codepen](https://codepen.io/AnotherLinuxUser/pen/jZOzZR?editors=0011) I provided would normally tell us if the `composition*` events are messing with AutoNumeric.

If we can't narrow down the cause in the next few days, and since the patch has fixed the current issue, I'll commit it and close that issue, and would need @nvanrooij to open a new one so we can track it.

**Comment by nvanrooij** [comment] 2018-02-08 09:40
My apologies @AlexandreBonneau, the last few days were a bit hectic, but I am planning on testing this afternoon!

**Comment by nvanrooij** [comment] 2018-02-08 15:50
Ok, I did some testing and this is what I found. I hooked up my tablet to my PC and used the Chrome Devtools to debug. When I use the onscreen keyboard this happens when typing "123":

`4.1.0-beta.24
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
i @ console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1
i @ console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1
i @ console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1
(anonymous) @ console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1
(anonymous) @ pen.js:10
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keydown: KeyboardEvent {isTrusted: true, key: "Unidentified", code: "", location: 0, ctrlKey: false, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 input: InputEvent {isTrusted: true, data: "1", isComposing: false, inputType: "insertText", dataTransfer: null, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keyup: KeyboardEvent {isTrusted: true, key: "Unidentified", code: "", location: 0, ctrlKey: false, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keydown: KeyboardEvent {isTrusted: true, key: "Unidentified", code: "", location: 0, ctrlKey: false, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 input: InputEvent {isTrusted: true, data: "2", isComposing: false, inputType: "insertText", dataTransfer: null, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keyup: KeyboardEvent {isTrusted: true, key: "Unidentified", code: "", location: 0, ctrlKey: false, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keydown: KeyboardEvent {isTrusted: true, key: "Unidentified", code: "", location: 0, ctrlKey: false, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 input: InputEvent {isTrusted: true, data: "3", isComposing: false, inputType: "insertText", dataTransfer: null, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keyup: KeyboardEvent {isTrusted: true, key: "Unidentified", code: "", location: 0, ctrlKey: false, …}`

After clicking somewhere outside the textfield the entry is removed.

When I use the emulator / screen mirror in Chrome and I type in 123 using my physical keyboard I get:

`console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 4.1.0-beta.24
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
i @ console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1
i @ console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1
i @ console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1
(anonymous) @ console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1
(anonymous) @ pen.js:10
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keydown: KeyboardEvent {isTrusted: true, key: "1", code: "Digit1", location: 0, ctrlKey: false, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 autoNumeric:rawValueModified -> rawValue: 1
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 input: CustomEvent {isTrusted: false, detail: null, type: "input", target: input.an, currentTarget: input.an, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keypress: KeyboardEvent {isTrusted: true, key: "1", code: "Digit1", location: 0, ctrlKey: false, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keyup: KeyboardEvent {isTrusted: true, key: "1", code: "Digit1", location: 0, ctrlKey: false, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keydown: KeyboardEvent {isTrusted: true, key: "2", code: "Digit2", location: 0, ctrlKey: false, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 autoNumeric:rawValueModified -> rawValue: 12
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 input: CustomEvent {isTrusted: false, detail: null, type: "input", target: input.an, currentTarget: input.an, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keypress: KeyboardEvent {isTrusted: true, key: "2", code: "Digit2", location: 0, ctrlKey: false, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keyup: KeyboardEvent {isTrusted: true, key: "2", code: "Digit2", location: 0, ctrlKey: false, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keydown: KeyboardEvent {isTrusted: true, key: "3", code: "Digit3", location: 0, ctrlKey: false, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 autoNumeric:rawValueModified -> rawValue: 123
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 input: CustomEvent {isTrusted: false, detail: null, type: "input", target: input.an, currentTarget: input.an, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keypress: KeyboardEvent {isTrusted: true, key: "3", code: "Digit3", location: 0, ctrlKey: false, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keyup: KeyboardEvent {isTrusted: true, key: "3", code: "Digit3", location: 0, ctrlKey: false, …}`

After using my mouse in the emulator (or when I click on my tablet) 123 gets changed to 123.00.

Clearly something is not happening when using the Samsung keyboard. I then installed a Gboard, to see if that would make a difference, but unfortunately not. I hope this log helps. If you need more information, or want to see what happens using a teamviewer session please let me know.

**Comment by AlexandreBonneau** [comment] 2018-02-09 08:20
Thanks for this log @nvanrooij. Using it, I might have found a solution, if we are lucky ;)

Would you guys please test [this new codepen](https://codepen.io/AnotherLinuxUser/pen/LQxvGe?editors=0011) with some changes that, hopefully, should fix the old android problem?

Thanks!

**Comment by alexturpin** [comment] 2018-02-09 14:23
That one doesn't apply any formatting for me on Android @AlexandreBonneau. Just acts like a regular text box.

**Comment by nvanrooij** [comment] 2018-02-09 14:55
Unfortunately this latest codepen didn't change anything @AlexandreBonneau:

`4.1.0-beta.25
DevTools failed to parse SourceMap: https://rawgit.com/AlexandreBonneau/8ba66496e891012b9c32522c99b26598/raw/51279afce1427e7d609b0d0971aa687d9f484db1/autoNumeric.min.js.map
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
i @ console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1
i @ console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1
i @ console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1
(anonymous) @ console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1
(anonymous) @ pen.js:10
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keydown: KeyboardEvent {isTrusted: true, key: "Unidentified", code: "", location: 0, ctrlKey: false, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 input: InputEvent {isTrusted: true, data: "1", isComposing: false, inputType: "insertText", dataTransfer: null, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keyup: KeyboardEvent {isTrusted: true, key: "Unidentified", code: "", location: 0, ctrlKey: false, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keydown: KeyboardEvent {isTrusted: true, key: "Unidentified", code: "", location: 0, ctrlKey: false, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 input: InputEvent {isTrusted: true, data: "2", isComposing: false, inputType: "insertText", dataTransfer: null, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keyup: KeyboardEvent {isTrusted: true, key: "Unidentified", code: "", location: 0, ctrlKey: false, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keydown: KeyboardEvent {isTrusted: true, key: "Unidentified", code: "", location: 0, ctrlKey: false, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 input: InputEvent {isTrusted: true, data: "3", isComposing: false, inputType: "insertText", dataTransfer: null, …}
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 keyup: KeyboardEvent {isTrusted: true, key: "Unidentified", code: "", location: 0, ctrlKey: false, …}`

**Comment by AlexandreBonneau** [comment] 2018-02-09 19:23
Well, 💩.

I'll push the fix for this issue, and since some stubborn Chrome developers [do not want to fix the bug](https://bugs.chromium.org/p/chromium/issues/detail?id=118639) is their keyboard management implementation, we'll either have to:
1. Ignore the Android version(s) that are bugging (which version exactly are we talking about, and what % of the marketshare does that represent?), or
2. Hack our way around the Android Chrome limitation by:
    1. Sniffing the user agent
    2. Let the user enter anything
    3. Checking the character inserted after the caret
    4. Remove that caret if not allowed
    5. or accept it (which means 1) unformatting the whole input field, then 2) using `set()` with the unformatted value, and lastly 3) correctly set the new caret position that must be calculated based on it previous position in the initial formatted content...)

That would be a painful and dirty hack 😢

**Comment by AlexandreBonneau** [comment] 2018-02-09 19:45
For info, Android Chrome does not send any `composition*` events when entering characters in the input textfield (see [this codepen](https://codepen.io/AnotherLinuxUser/pen/zRZzrV?editors=1011)).

😫

**Comment by AlexandreBonneau** [comment] 2018-02-10 09:22
Ok so I fixed that issue and the bug where on Android Chrome blurring the input would clear the value.

It's now live in `v4.1.0-beta.26`!
*(you can check the [latest codepen](https://codepen.io/AnotherLinuxUser/pen/xYqJBO?editors=1011) too see it in action)*

Please test on you end and report any problem you find, thanks!

> Note:
There is still one known issue (that needs be [created](https://github.com/autoNumeric/autoNumeric/issues/new) by the way ;)) on Android Chrome; if you cut a part of the number, then an `input` event is sent with an inputType `deletedByCut`, and since it was not cut with `ctrl+x`, AutoNumeric does not see that correctly and does not update the `rawValue`.

**Closed by AlexandreBonneau** 2018-02-10 09:22 UTC
Labels: Bug, Important!, In progress, Mobile

**Comment by nvanrooij** [comment] 2018-02-12 12:57
Great work @AlexandreBonneau ! I don't know how you did it, but it seems to be working for me 👍

**Comment by AlexandreBonneau** [comment] 2018-02-12 19:36
Magic! :godmode:

:trollface:
