### ISSUE TITLE
Selenium IDE does not record type input field (using autonumeric.js) 

### ISSUE THREAD

**Issue by antonio-bakula** [autoNumeric/autoNumeric#199] opened 2016-04-07 22:06 UTC
Selenium is popular tool for automated testing, and Selenium IDE is firefox extension that records selenium test cases.
Download Selenium IDE from [https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/](https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/)
1. Record test on page http://www.decorplanit.com/plugin/
2. Enter something in any of numeric fields, for example in Euro- Germany field
3. Nothing is recorded
4. Paste number in that same field, IDE recorded that as a type command

Here is a short video:http://screencast.com/t/j2sI0RjTNv4

**Comment by BobKnothe** [comment] 2016-04-10 21:58
Interesting - thanks for the screen cast very helpful.

Not sure when I can find the time to find the cause.

**Comment by antonio-bakula** [comment] 2016-04-10 22:54
Could you point me in right direction, what events autoNumeric suppres ? I have special build for tests so maybe I can fire that events and hopefully Selenium will record that.

**Comment by BobKnothe** [comment] 2016-04-11 21:52
Well without any testing on my part it would be a guess.

I would need to go back to old versions and test and see what changes 
were made and when some of the events did not bubble up. Version 1.8 & 
1.9 were big mile stones

**Comment by antonio-bakula** [comment] 2016-04-12 09:34
OK, tnx, I tried with 1.9.43 and 2.0, will try with 1.8 and earlier

**Comment by antonio-bakula** [comment] 2016-04-12 12:44
I tried: 
1.8.9. - don't work
1.8.2. - don't work
1.7.0 - don't work
1.6.2 - works !

I will try to see what are the differences between 1.6.2 and 1.7.0...

**Comment by BobKnothe** [comment] 2016-04-12 13:35
Thanks for checking. 

 
Robert (Bob) Knothe

**Comment by antonio-bakula** [comment] 2016-04-12 13:36
It's keypress event, I commented part in keypress handler that preventsDefault and returns false if holder processed allways or keypress and Selenium works again. It seems that autoNumeric also works OK but who knows what else I broken, here is the screenshot of commented code:

[http://screencast.com/t/tk6V45Mu87kp](http://screencast.com/t/tk6V45Mu87kp)

I will report this to Selenium team also, maybe they will have some sort of solution, thanks.

**Comment by movalz** [comment] 2016-12-01 16:00
I have same issue with PrimeFaces 6.0.9 and done some further investigation with following result:
It's possible to detect if we are currently running with opened SeleniumIDE Recorder (via "if (window['_Selenium_IDE_Recorder'])"). So I have patched event handler for 'keypress.autoNumeric' and surrounded the relevant if statement with that check:
```
if (!window['_Selenium_IDE_Recorder']) {
    if (holder.processAllways() || holder.processKeypress()) {
        holder.formatQuick();
        e.preventDefault();
        return false;
    }
}
```
This fixes the recording issue for me, with the side effect that filtering of bad key strokes is done with some delay (and sometimes entering the decimal point shows strange input temporarely and/or backspace or del key doesn't function). These side effects are ok for me when recording with Selenium IDE but not with a real user. With the detection of SeleniumIDE Recorder I can live with this for the moment, but would be very happy about a clean solution of this issue. The reason is (AFAIK) the call of e.preventDefault();. But removing this statement would put every pressed key twice into the field.

By the way: for replaying a recorded or manually created SeleniumIDE test the input to a p:inputNumber field has another issue which is described in https://github.com/primefaces/primefaces/issues/1940 (incl. a similar workaround).

**Comment by AlexandreBonneau** [comment] 2016-12-08 08:32
An issue has been opened about native `input` and `change` events not being sent correctly.

We'll have to check this problem again once issue #292 is solved.

**Comment by AlexandreBonneau** [comment] 2016-12-22 12:00
@antonio-bakula Could you please check again if fixing #292 also fixed that issue?

Thanks!

**Comment by antonio-bakula** [comment] 2016-12-29 22:00
Sorry for late answer but I am afraid that this is not fixed with fix for #292. I tried with jquery 1.12.4, 2.2.4 and 3.1.1 and used autonumeric from next branch. Here is the sample I tested on:

[http://www.antoniob.com/easyedit/userfiles/autonumeric/index.html](http://www.antoniob.com/easyedit/userfiles/autonumeric/index.html)

**Comment by AlexandreBonneau** [comment] 2016-12-30 01:44
Indeed, nothing is recorded.
I'm not sure what is the cause of this problem.
Selenium should be able to access the `input.value` value, since this is modified correctly by autoNumeric.

**Comment by AlexandreBonneau** [comment] 2016-12-30 02:00
I've created an issue in the selenium repository, hopefully they will be able to narrow down why Selenium IDE is not picking up those inputs.

**Comment by AlexandreBonneau** [comment] 2017-08-31 22:32
It's sad, but apparently Selenium IDE is discontinued on Firefox, for the time being.
The project just closed the issue I opened before, and is now referring to a [new issue](https://github.com/SeleniumHQ/selenium/issues/4406) that will follow how and when they'll manage to convert the extension to WebExtensions.

I'll close this issue for the time being.
Be sure to check again if AutoNumeric is at fault when the new WebExtensionnized Selenium IDE app is released!

**Closed by AlexandreBonneau** 2017-08-31 22:32 UTC
Labels: Bug, Wait for other project
