### ISSUE TITLE
The DOM element is not valid, [object HTMLInputElement] given.

### ISSUE THREAD

**Issue by michaeltintiuc** [autoNumeric/autoNumeric#537] opened 2017-12-08 18:25 UTC
### Expected behavior
Trying to initialize autoNumeric as per examples in readme:
`new AutoNumeric('.myInput');`

### Actual behavior
`Error: The DOM element is not valid, [object HTMLInputElement] given.`

### Steps to reproduce the problem
1. Using autoNumeric `<v4.0.3>` and the browser `<Firefox>` version `<57.0.1>` on `<Linux>`,
2. I used no options
3. Initialized my AutoNumeric object with the call `<new AutoNumeric(domElement)>`,
4. `Error: The DOM element is not valid, [object HTMLInputElement] given.`

By looking at the source I can see that the `checkElement` is only checking `domElement typeof Element` when for some reason the string `myInput` passed to AutoNumeric results in HTMLInputElement object.

**Comment by AlexandreBonneau** [comment] 2017-12-08 18:29
Hey @michaeltintiuc, could you create a reproducible example of the problem on codepen please?

**Comment by michaeltintiuc** [comment] 2017-12-08 20:30
@AlexandreBonneau The issue is that I can not reproduce this, if I do a `myElement instanceof Element` on any DOM element in the app I always get false.

**Comment by AlexandreBonneau** [comment] 2017-12-08 21:09
Well, if you can't reproduce the *'bug'*, then I cannot fix it if it indeed from AutoNumeric!

See, I created a [very simple test case here](https://codepen.io/AnotherLinuxUser/pen/MONyzG?editors=1010), and do not see the problem neither with Firefox `58.0b9`, `58.0b10`, `56.0b12` nor `52.5.0`, with the stable or `next` AutoNumeric versions.

I'm therefore closing this as invalid. If you feel you can add more data so we can reproduce (and fix eventually) this, then feel free to reopen that issue.

Lastly, [`HTMLInputElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement) is subclassing [`Element`](https://developer.mozilla.org/en-US/docs/Web/API/Element), so your `instanceof` test must be wrong somewhere, see in the codepen:
```js
console.log('Element: ', inputNode instanceof Element); // true
console.log('HTMLInputElement: ', inputNode instanceof HTMLInputElement); // true
```

**Closed by AlexandreBonneau** 2017-12-08 21:09 UTC
Labels: Need user input

**Comment by michaeltintiuc** [comment] 2017-12-08 21:18
@AlexandreBonneau Thanks for your reply, I was able to finally pin point the issue, the legacy code-base was using Prototype.js which overwrote the native Element function :(

**Comment by AlexandreBonneau** [comment] 2017-12-10 03:15
Any time!
