### ISSUE TITLE
Uncaught Error: `_initialCaretPosition()` should never be called when the `caretPositionOnFocus` option is `null`.

### ISSUE THREAD

**Issue by wc-matteo** [autoNumeric/autoNumeric#455] opened 2017-06-09 09:59 UTC
### Expected behavior
Focusing on a field doesn't cause a javascript exception

### Actual behavior
Focusing on a field causes a javascript exception

### Steps to reproduce the problem
1. Using autoNumeric `4.0.0-beta.20` and the browser `Chrome` version `58` on `Windows`,
2. I used the options `{ selectOnFocus: false }`, and 
3. Initialized my AutoNumeric object with the call `  AutoNumeric.multiple('input', options)`,
4. Then my computer exploded, for real.

### Observations
Setting `selectOnFocus` to false causes the issue and not setting it or setting it to true doesn't cause it.

**Comment by AlexandreBonneau** [comment] 2017-06-09 10:11
Hey @wc-matteo, thanks for reporting this.

Could you tell us more about how to reproduce the problem? (a codepen would be even better!)
For instance, what's the value of `format.group` and `format.decimal`?
What is the html structure and tags having the `data-wc-type-number` attribute on them?

When you say:
> Not setting `selectOnFocus` to `false` doesn't cause the issue

Do you mean that setting `selectOnFocus` to `true` does cause the issue?

Sorry about the explosion :/

**Comment by wc-matteo** [comment] 2017-06-09 10:22
> Do you mean that setting selectOnFocus to true does cause the issue?

Sorry for the twisted sentence. I meant the setting to false causes the issue and that not setting or setting it to true doesn't cause it (because the default is true).

I tried to reproduce it taking out all custom options but `selectOnFocus: false`. You should be able to reproduce it just as easily. If not, I'll make a pen.

**Comment by AlexandreBonneau** [comment] 2017-06-09 10:24
So you can reproduce the bug using just that option object?:
```js
{ selectOnFocus: false }
```

**Comment by AlexandreBonneau** [comment] 2017-08-01 00:49
@wc-matteo were you able to reproduce the bug with the latest stable version `v4.0.1`?

**Comment by wc-matteo** [comment] 2017-08-01 07:10
@AlexandreBonneau sorry, don't have time to test right now...

**Comment by AlexandreBonneau** [comment] 2017-08-09 00:40
I'm closing this issue for now, since I cannot reproduce it.
Feel free to reopen it if you can provide a codepen showing the problem!

**Comment by Enkindler** [comment] 2017-10-09 13:38
I was able to reproduce this issue, can we reopen it?.

**Steps to reproduce**
Options variable:
{
     digitGroupSeparator: __separadorMiles,
     decimalCharacter: __caracterDecimal,
     currencySymbol	: __simboloMoneda,
     minimumValue: 0,
     leadingZero: 'deny',
     selectOnFocus: 'false',
     modifyValueOnWheel: false
}

The inputs are initialized with: new Autonumeric(this, optionVar);

When selecting an input to edit, the error is displayed on console. This ocurrs with all inputs initialized with the previous option var. Eliminating selectOnFocus from the options var removes the error

**Comment by AlexandreBonneau** [comment] 2017-10-11 02:13
Fixed in `next`!

Thanks for updating this issue :)

**Closed by AlexandreBonneau** 2017-10-11 02:13 UTC
Labels: Bug
