### ISSUE TITLE
Bug on form reset

### ISSUE THREAD

**Issue by rui-ribeiro** [autoNumeric/autoNumeric#219] opened 2016-06-08 15:08 UTC
Hi,

autoNumeric 2.0beta have a bug on form reset. After you reset the form and focusin the input the last value returns.

I have created a demo. Just type something, clear form and then click on the input.

https://github.com/rui-ribeiro/autoNumeric-bug

Thanks :)

**Comment by BobKnothe** [comment] 2016-06-08 20:54
Thanks you.

Did not catch in my testing - will fix and post

**Comment by BobKnothe** [comment] 2016-06-09 10:53
I am hoping you could test this fix - place it above the submit event approx line 1518

					$this.closest('form').on('reset.autoNumeric', function () {
						holder = getHolder($this);
						if (holder) {
							$this.autoNumeric('wipe');
							var reSet = function() {
								$this.autoNumeric('set', $this.val());
							};
							setTimeout(reSet, 100);
						}
					});

It uses setTimeout which I am not thrilled about

**Comment by rui-ribeiro** [comment] 2016-06-09 11:12
That works.

But why not only this:

```javascript
$this.closest('form').on('reset.autoNumeric', function () {
   $this.autoNumeric('wipe');
});
````

That works to.

**Comment by BobKnothe** [comment] 2016-06-09 11:19
Can you test on multiple browsers?

**Comment by rui-ribeiro** [comment] 2016-06-09 12:54
Well, I only tested on chrome.

Version: 51.0.2704.84 m

But Yes, I will test on different browsers

2016-06-09 12:19 GMT+01:00 Bob Knothe <notifications@github.com>:

**Comment by BobKnothe** [comment] 2016-06-23 01:10
I have done some testing and the only way to have the default values formatted on reset is the use setTimeout.

Have you found any other solution?

**Comment by AlexandreBonneau** [comment] 2016-12-24 11:35
Is this bug still present in the latest `next` branch?

**Comment by AlexandreBonneau** [comment] 2017-03-17 19:19
Due to inactivity, I'm closing this issue considering it resolved.

If that's not the case, feel free to re-open it!

**Comment by ducman** [comment] 2018-03-06 23:16
I wish this was a part of autoNumeric instead of us having to do this.

**Comment by AlexandreBonneau** [comment] 2018-03-07 06:05
@ducman if you feel that there is a bug in AutoNumeric, please open an issue!

**Comment by ducman** [comment] 2018-03-07 18:00
@AlexandreBonneau, can we re-open this issue instead of creating a new one (lazy)?

Here is the [codepen](https://codepen.io/ducman/pen/oqvxJy?editors=1011) outlining the issues.
1. Form reset does reset the input back to its original value but there is no autonumeric formatting.
2. After doing above (1), hovering over the input added the formatting, but it format the wrong value. Step to reproduce below.

Step to reproduce for (2)
1. Go to the above code pen.
2. Notice the default value (1,234.00).
3. Modify it to a different value (i.e. 1,111.00).
4. Click the reset button.
5. Notice the default value (1234) re-appear on the input but un-formatted.
6. On hover over the input, the input is formatted with $1,111.00 instead of $1,234.00.

**Comment by AlexandreBonneau** [comment] 2018-03-07 19:28
Thanks for the reproducible test case @ducman.

This is indeed a bug :)

**Comment by ducman** [comment] 2018-03-13 06:31
Just an FYI, the above sample fix from @BobKnothe, doesn't seem to work. I'm sorry I don't have any example to show but the UI looks fine but on post after a reset, the input value was empty. I think the use of `wipe` messed it up.

I ended up using something below and I still had to use a `setTimeout`.
```js
setTimeout(() => anElement.set($('input').prop('defaultValue')), 100);

**Comment by AlexandreBonneau** [comment] 2018-07-28 02:31
For info, from the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/reset):

> *You should usually avoid including reset buttons in your forms. They're rarely useful, and are instead more likely to frustrate users who click them by mistake (often while trying to click the submit button).*

So I added a fix for this bug, although ideally this should never be used :smirk:

**Closed** 2018-07-28 02:31 UTC
Labels: :beetle: Bug, :construction: In progress
