### ISSUE TITLE
Input in Chrome on Android results in random characters being inserted

### ISSUE THREAD

**Issue by alexturpin** [autoNumeric/autoNumeric#540] opened 2018-01-05 01:09 UTC
### Expected behavior
If I type "1234" with my options below I expect to see "1,234" in the field.

### Actual behavior
On Chrome on Android, random digits get inserted as I am typing and the end result is "112.43". I also have to go back into the numerical keyboard after typing the first "1".
I made a recording to showcase the issue: https://www.youtube.com/watch?v=1Zn4g-8MZpc

### Steps to reproduce the problem
1. Using autoNumeric `4.0.3` and the browser `Chrome for Android` version `63.0.3239.111` on `Android 8.1.0`,
2. I used the options 
```
{
	digitGroupSeparator: ",",
	decimalCharacter: ".",
	currencySymbol: "",
	currencySymbolPlacement: "p",
	decimalPlaces: 2,
	minimumValue: -999999999.99,
	maximumValue: 999999999.99,
	selectOnFocus: false,
	modifyValueOnWheel: false
}
```
3. Initialized my AutoNumeric object with the call
```
new AutoNumeric(document.querySelector('#test'), {
	digitGroupSeparator: ",",
	decimalCharacter: ".",
	currencySymbol: "",
	currencySymbolPlacement: "p",
	decimalPlaces: 2,
	minimumValue: -999999999.99,
	maximumValue: 999999999.99,
	selectOnFocus: false,
	modifyValueOnWheel: false
});
```
4. This seems to be happening both in `master` and in `next` branches

### Link to live example
Very straightforward: https://codepen.io/anon/pen/VyMMKL

I will start digging into the AutoNumeric code to see what might be the cause as this is a critical issue for us. However, as this will be one of my first forays into that code, I wanted to get this issue out first so if anyone has any idea we can get this fixed sooner. Any hints are appreciated.

**Comment by AlexandreBonneau** [comment] 2018-01-05 01:43
Thanks for reporting that issue and taking the time to create the screencast and live example @alexturpin.

That bug however is known and a duplicate of issue #522.
I'll close this one any followup should be added to that issue.
If you feel this one is somehow different, feel free to reopen it.

We know that the Android support is not perfect and need to be addressed asap (disclaimer; manipulating user entries under Android is a pain, and testing changes on that platform is also complex since we did not found the time to setup browserstack properly).


Bonus, instead of using:
```js
new AutoNumeric(document.querySelector('#test'), yourOptions);
```
you can use:
```js
new AutoNumeric('#test', yourOptions);
```
directly since AutoNumeric will query the element if a `String` is detected as its first argument.

**Closed by AlexandreBonneau** 2018-01-05 01:43 UTC

**Comment by alexturpin** [comment] 2018-01-05 01:49
Sorry about the duplicate! I did a search and didn't find anything. Thanks for pointing me to the other issue!

**Comment by AlexandreBonneau** [comment] 2018-01-05 01:50
Additionally, if you want to dig in the AutoNumeric code, I'd suggest to take a look at the [`_onInput()`](https://github.com/autoNumeric/autoNumeric/blob/64639f726ae04fd84c49097461fc4d8febacaac8/src/AutoNumeric.js#L6246) method that handle key events on the Android platform (where the keycodes for every key equals `229`...).

Also, check the [event lifecycle doc](https://github.com/autoNumeric/autoNumeric/tree/next#event-lifecycle) for info and run `yarn test:unitpp` to be sure that your changes does not break the desktop.

Have fun ;)

**Comment by alexturpin** [comment] 2018-01-08 19:23
Alternatively to solve this issue, does anyone know if it's possible to have AutoNumeric only format the number on blur and not as text is being entered? That would probably be enough to solve the issue for us, but I can't seem to find the right option in the docs. The problem still occurs with `showOnlyNumbersOnFocus`, my guess is because it still does decimal formatting.

**Comment by AlexandreBonneau** [comment] 2018-01-09 00:21
I do not recommend doing that, since you'd lose the main goal of AutoNumeric ; formatting *as-you-type*.

However if you want to go down this road, you *could* set the `noEventListeners` option to `true` (see the [doc](https://github.com/autoNumeric/autoNumeric/tree/next#noeventlisteners)), and manually add an event listener on `blur` that calls the `anElement.set(yourValue)` method.

**Comment by alexturpin** [comment] 2018-01-09 00:24
> I do not recommend doing that, since you'd lose the main goal of AutoNumeric ; formatting as-you-type.

Unfortunately this issue with Android is serious enough that it is making us completely disable AutoNumeric for Android. And from what I can tell the issue happens because of cursor manipulation to do the formatting as-you-type. So for us at least we aren't losing functionality by doing this but actually gaining some 😄 

Thanks for the suggestion, I'll give that a go.
