### ISSUE TITLE
Change event not firing depending on cursor movement

### ISSUE THREAD

**Issue by bforsythe** [autoNumeric/autoNumeric#596] opened 2018-07-25 18:12 UTC
Hello again!  Our team ran into a fun little bug in >=4.2.5 versions of AutoNumeric.  Our users that rely heavily on touchpads found the problem (you'll understand why when you see the repro steps), and after quite a bit of debugging, we're glad to say we can reproduce the issue. However I haven't had the time to try to come up with a fix (sorry).  

I will preface this by saying we've come up with an immediate workaround by changing our number/money components to rely on the 'autoNumeric:rawValueModified' event instead of the native 'change' event.  Unfortunately it is a behavioral change (live updates vs. waiting for a blur), but it's one I think we can deal with for now.

Steps to repro:
Enter a value in an autonumeric field (leave the field focused)
Move the cursor out of the field
Move the cursor back into the field
Move the cursor out of the field
Click to blur the field
Change event did not fire

https://imgur.com/W21UO6Z
See the linked gif where I demonstrate that the change event fires when normally entering a value of 45 then blurring the field, but then following the steps above, the change event does not fire even though the value has changed from 45 to 46. 

https://jsfiddle.net/bforsythe/hkc5zau2/2/
Linked is also the jsfiddle I used to reproduce (it's kind of slow since I dumped the latest Autonumeric in a <script> with some console logging to help show/debug the issue).

The bug appears to have been introduced in: https://github.com/autoNumeric/autoNumeric/commit/cc04b414fcfcfda149daabcf0539403798944dc0
--where the rawValueOnFocus concept was introduced to avoid duplicate change events.

Because rawValueOnFocus was set to be the value of the field when my cursor re-entered the field, when the blur happens rawValue == rawValueOnFocus, and change is not fired.

If you need any more information please let me know.
Thanks again,
Brandon

**Comment by AlexandreBonneau** [comment] 2018-07-25 20:16
Thanks for the complete and thorough bug report @bforsythe; the problem is well identified!
I'll see what I can do :)

**Comment by AlexandreBonneau** [comment] 2018-07-25 20:36
Whoops I committed a bit to quickly, I just found a related bug once I pushed that 'fix'..

**Comment by AlexandreBonneau** [comment] 2018-07-25 20:54
This should be fixed in `v4.3.5`!

**Closed by AlexandreBonneau** 2018-07-25 20:54 UTC
Labels: :beetle: Bug

**Comment by AlexandreBonneau** [comment] 2018-07-25 20:59
Too bad we do not have regression test for mouse movements in our end-to-end tests.
Webdriver.io provided the deprecated `moveTo()` function, but if you guys knows about a way to automate this kind of tests, please post here or create a PR!

**Comment by bforsythe** [comment] 2018-07-26 13:29
Thanks for the quick fix!  I can't say we've done explicit mouse movement before in our UI tests so we can't offer much guidance there, however it looks like Actions may support that behavior (http://webdriver.io/api/protocol/actions.html), I haven't had a chance to try it out though.

Thanks again, Brandon
