### ISSUE TITLE
Minimum behaves wierd

### ISSUE THREAD

**Issue by beckmx** [autoNumeric/autoNumeric#636] opened 2019-03-12 01:06 UTC
### Current behavior
The minimum is expecting a bigger value

### Expected behavior
it should allow you to write values such as the previous numbers

### Steps to reproduce the problem
1. Use autoNumeric version `4.5.4`
2. In the browser `Chrome` version `72.0.3626.121 (Official Build) (64-bit)`
3. On the `MacOS` operating system
4. Then instantiate the autoNumeric object with the following options:
```js
new AutoNumeric(domElement, { minimum:3 });
```
5. I want to type 33 or 21 or whatever number with 1,2 or 3 and it won't write, I understand it is hunting the minimum but it doesnt quite work that approach

**Comment by AlexandreBonneau** [comment] 2019-03-12 06:06
It seems your issue is a duplicate of https://github.com/autoNumeric/autoNumeric/issues/543

**Closed by AlexandreBonneau** 2019-03-12 06:06 UTC
Labels: :triangular_flag_on_post:  Duplicate
