### ISSUE TITLE
Failing unit tests on macOS with German localization

### ISSUE THREAD

**Issue by DanielRuf** [autoNumeric/autoNumeric#607] opened 2018-09-13 10:09 UTC
### Current behavior
<Please describe here what faulty behavior you are experiencing>
On macOS with German localization the unit tests fail.

### Expected behavior
<Please describe here the expected behavior>
The unit tests should succeed.

### Steps to reproduce the problem
1. clone autoNumeric and run `yarn && yarn test`

```
FAILED TESTS:
  The AutoNumeric object
    initialization methods
      ✖ should correctly initialize the AutoNumeric element when the `formatOnPageLoad` option is set
        Firefox 61.0.0 (Mac OS X 10.13.0)
      Expected '12234678.321' to equal '$12,234,678.32'.
      <Jasmine>
      ./test/unit/autoNumeric.spec.js/</</<@webpack://autonumeric/test/unit/autoNumeric.spec.js:1150:12 <- tests.webpack.js:9:705409
      <Jasmine>

  Initialization calls
    Initialize a single AutoNumeric object
      ✖ should fail to init when the default value is outside of the min and max limits
        PhantomJS 2.1.1 (Mac OS X 0.0.0)
      TypeError: undefined is not an object (evaluating 'aNInput.remove') in tests.webpack.js (line 9)
      webpack://autonumeric/webpack/universalModuleDefinition:1:0 <- tests.webpack.js:9:1481375
      <Jasmine>

  autoNumeric options and `options.*` methods
    `options.*` methods
      ✖ should correctly update the `decimalPlacesShownOnFocus` option
        Firefox 61.0.0 (Mac OS X 10.13.0)
      Expected '2.222,12 €' to equal '2.222,1235 €'.
      <Jasmine>
      ./test/unit/autoNumeric.spec.js/</</<@webpack://autonumeric/test/unit/autoNumeric.spec.js:1483:12 <- tests.webpack.js:9:734042
      <Jasmine>

  Instantiated autoNumeric functions
    `selectInteger`
      ✖ should select only the decimal part
        Firefox 61.0.0 (Mac OS X 10.13.0)
      Expected '12.266,123 €' to equal '12.266,123457 €'.
      <Jasmine>
      ./test/unit/autoNumeric.spec.js/</</<@webpack://autonumeric/test/unit/autoNumeric.spec.js:5157:12 <- tests.webpack.js:9:990807
      <Jasmine>

  The AutoNumeric event lifecycle
    ✖ should send the 'autoNumeric:formatted' event when formatting is done
      Firefox 61.0.0 (Mac OS X 10.13.0)
    Expected spy formattedEvent to have been called 6 times. It was called 5 times.
    <Jasmine>
    ./test/unit/autoNumeric.spec.js/</<@webpack://autonumeric/test/unit/autoNumeric.spec.js:8420:8 <- tests.webpack.js:9:1305434
    <Jasmine>
```

I'll try to investigate this further.

**Comment by AlexandreBonneau** [comment] 2018-09-14 01:28
What's your locale exactly?

On Linux you can find out using `locale`.
For instance on my system:
```
» locale
LANG=fr_FR.UTF-8
LANGUAGE=fr:en_US
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=fr_FR.UTF-8
```

**Comment by DanielRuf** [comment] 2018-09-14 06:04
```
locale
LANG="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_CTYPE="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_ALL=
```

**Comment by AlexandreBonneau** [comment] 2018-09-24 06:36
Ok so for info, I added the `de_DE` locale to my system and ran the unit test, and I see 4 of those failing:
![2018-09-23_203521_screenshot](https://user-images.githubusercontent.com/7248877/45939682-31f23780-bf70-11e8-96c3-56480f33f019.png)

To see what is happening precisely, I installed the `firefox-esr-l10n-de` package, then followed [this guide](https://support.mozilla.org/de/questions/1018686) to change the default language of Firefox to german.
When I try to reproduce the bug on line 5157 manually, everything works correctly, which is unfortunate for resolving this issue.

I'll keep investigating..

**Comment by AlexandreBonneau** [comment] 2018-09-24 06:59
All the above issues stems from a faulty `domElement.focus()` behavior when using the `de_DE` locale.
This is really confusing, and I cannot find any particular info about that problem on the web.

What happens when you follow the unit tests manually on your computer @DanielRuf ? Can you successfully obtain the correct results?

I'm not sure how to proceed to 'fix' this bug, since from what I see this is not related to AutoNumeric, but how browsers handle the `.focus()` method.

**Comment by DanielRuf** [comment] 2018-09-24 07:06
I doubt that this is related to `focus()` but to `toLocaleString()` probably.

**Comment by AlexandreBonneau** [comment] 2018-09-27 19:57
I'm not using `toLocaleString()` anywhere, and all those errors are happening *exactly* after a call to `focus()`, which should correctly send the `focus` event, which in turn should have been caught by AutoNumeric to reformat the value.
But since somehow `domElement.focus()` does not correctly send the `focus` event, the value are not reformatted, hence the errors you get.

Does those errors happens when you manually do the faulty tests?

**Comment by AlexandreBonneau** [comment] 2018-09-27 21:28
There shouldn't be indeed, however I'm using `fr_FR` by default and I do not see that bug

**Comment by DanielRuf** [comment] 2018-09-27 21:38
Also latest stable (Chrome 69 and FF latest)?

I'll investigate further.

**Comment by AlexandreBonneau** [comment] 2018-09-27 21:48
Yes, I run Chromium `69.0.3497.92-1` and the Firefox dev edition (which is `63.0b9` as of now).

**Comment by DanielRuf** [comment] 2018-09-28 06:17
Not sure how I should run them manually as there is no browser entry point in the tests directory for browser based testing.

Manually copying parts is not very efficient.

**Comment by DanielRuf** [comment] 2018-09-28 06:45
Current results with `yarn test`:

```
FAILED TESTS:
  autoNumeric options and `options.*` methods
    `options.*` methods
      ✖ should correctly update the `decimalPlacesShownOnFocus` option
        Firefox 62.0.0 (Mac OS X 10.13.0)
      Expected '2.222,12 €' to equal '2.222,1235 €'.
      <Jasmine>
      ./test/unit/autoNumeric.spec.js/</</<@webpack://autonumeric/test/unit/autoNumeric.spec.js:1483:12 <- autoNumeric.js:9:734083
      <Jasmine>

  The AutoNumeric object
    initialization methods
      ✖ should correctly initialize the AutoNumeric element when the `formatOnPageLoad` option is set
        Firefox 62.0.0 (Mac OS X 10.13.0)
      Expected '12234678.321' to equal '$12,234,678.32'.
      <Jasmine>
      ./test/unit/autoNumeric.spec.js/</</<@webpack://autonumeric/test/unit/autoNumeric.spec.js:1150:12 <- autoNumeric.js:9:705450
      <Jasmine>

  Instantiated autoNumeric functions
    `selectInteger`
      ✖ should select only the decimal part
        Firefox 62.0.0 (Mac OS X 10.13.0)
      Expected '12.266,123 €' to equal '12.266,123457 €'.
      <Jasmine>
      ./test/unit/autoNumeric.spec.js/</</<@webpack://autonumeric/test/unit/autoNumeric.spec.js:5157:12 <- autoNumeric.js:9:990848
      <Jasmine>

  The AutoNumeric event lifecycle
    ✖ should send the 'autoNumeric:formatted' event when formatting is done
      Firefox 62.0.0 (Mac OS X 10.13.0)
    Expected spy formattedEvent to have been called 6 times. It was called 5 times.
    <Jasmine>
    ./test/unit/autoNumeric.spec.js/</<@webpack://autonumeric/test/unit/autoNumeric.spec.js:8420:8 <- autoNumeric.js:9:1305475
    <Jasmine>

```

**Comment by AlexandreBonneau** [comment] 2018-09-28 07:08
Being able to run the test automatically with `yarn test:unit` is indeed the better way to run those.

Meanwhile, you could open the test page `./autoNumeric/test/e2e/index.html`, then *manually* create the inputs by copying the javascript lines from `autoNumeric.spec.js` into the console.
I know this is not optimal, but at least it could tell us if the bug is happening when you use AutoNumeric with 'real' interactions.

**Comment by AlexandreBonneau** [comment] 2018-12-02 12:38
Hey @DanielRuf, have you had time to run the test manually and check if they pass?

**Comment by AlexandreBonneau** [comment] 2019-01-03 09:31
Due to inactivity, this issue has been marked for deletion and will be closed in the next few days.
Please give us more information if you feel the problem still affects you.

**Comment by DanielRuf** [comment] 2019-01-03 09:49
> marked for deletion

Issues should be never deleted. This new feature is just meant if an issue contained confidential details.

So far I had not yet the time for further tests and bisecting.

**Comment by DanielRuf** [comment] 2019-01-03 09:51
https://twitter.com/github/status/1060233780114288640

**Comment by AlexandreBonneau** [comment] 2019-01-04 08:19
@DanielRuf my bad, I created the `Marked for deletion` label, but in reality it should read `marked for closing`, or something like this.
I never ever deleted an issue; as you mention, it's pretty irresponsible to delete issues from an issue tracker (except perhaps in the case of credentials being pasted)!

**Comment by AlexandreBonneau** [comment] 2019-01-04 08:34
There is no script nor bots, just me checking the issues from time to time, and if *'enough'* time has passed since a `Need reporter feedback` label has been set, then I use the [saved reply](https://help.github.com/articles/editing-a-saved-reply/) to 'ping' the fellow reporter ;)

Also, I totally get that allotting time to an open-source project can be challenging, specially if it requires some setup like I'm (gently) asking you, so, no worries ;)

**Closed** 2020-09-12 21:46 UTC
Labels: :beetle: Bug, :globe_with_meridians: i18n, :tipping_hand_man: Need reporter feedback, :warning:  Inactivity detected

**Comment by AlexandreBonneau** [comment] 2020-09-13 22:16
Hey Daniel, were the bugs still happening when running the tests automatically/manually?
