### ISSUE TITLE
Setting `unformatOnSubmit` to `true` does not unformat the element on the form' `submit` event

### ISSUE THREAD

**Issue by djbox3** [autoNumeric/autoNumeric#442] opened 2017-05-05 18:37 UTC
### Steps to reproduce the problem
1. Using autoNumeric `2.0.12` and the browser `Chrome or Firefox` version `<56.0.2924.87>` on `<Windows>`,
2. I used the options `{ unformatOnSubmit: true}`, and 
3. Initialized my AutoNumeric object with the call `new AutoNumeric(domElement, { options })`,
4. In an ASP page, I click submit button and server reads the input as `"$1.00"` instead of `"1.00"`.

**Comment by BobKnothe** [comment] 2017-05-05 19:41
@djbox3 

Thank you for the notice.

Question - is the input changed to '1.00' or remains '$1.00'?

**Comment by djbox3** [comment] 2017-05-05 22:06
The input still stays as $1.00. The server would read it as $1.00

**Comment by AlexandreBonneau** [comment] 2017-05-06 00:55
Hello @djbox3, would it be possible to test your problem with the latest autoNumeric version (on the `next` branch) ?

Also, if the problem persist, a codepen would be great to help us fix the bug!

Thanks

**Comment by djbox3** [comment] 2017-05-06 21:43
https://jsfiddle.net/L14k8cxa/

**Comment by AlexandreBonneau** [comment] 2017-05-07 01:03
Thanks for the live example ; I also managed to reproduce the bug in the `next` branch too (cf. [here](https://codepen.io/AnotherLinuxUser/pen/eWeWzQ?editors=1011)).

**Comment by AlexandreBonneau** [comment] 2017-05-07 03:30
This is fixed on the `next` branch!

Feel free to reopen this issue if you find that does not solve your problem.

**Closed by AlexandreBonneau** 2017-05-07 03:30 UTC
Labels: Bug

**Comment by wc-matteo** [comment] 2017-06-09 10:50
Just a note: with `AutoNumeric.multiple` an event listener gets attached for every input. When there are lots of inputs there will be lots of event listeners... this is not ideal. Are you aware of it?

**Comment by AlexandreBonneau** [comment] 2017-06-09 11:03
Indeed, this is not ideal and needs to be addressed.

From the top of my head, I see that this could get complex to manage though, if the user starts to remove some inputs from the shared list, if we were to only create one `submit` listener on the `form` element.

**Comment by wc-matteo** [comment] 2017-06-09 11:10
If the input is not on the shared list anymore, then it's value will not get unformatted. So when you submit a form, all active registered inputs get unformatted. Am I missing something?

**Comment by eternalBlast** [comment] 2019-04-24 09:42
if submit using <button type="submit"></button>, the unformatOnSubmit works well. However, if the
submit using <button type="button"></button> in case of some confirmation alert shown up first, the unformatOnSubmit not working.

**Comment by AlexandreBonneau** [comment] 2019-04-25 06:51
@eternalBlast this works as intended. `<button type="button"></button>` could be any button in the form, hence only the `type="submit"` is supported.
