### ISSUE TITLE
Not respecting maxlength

### ISSUE THREAD

**Issue by marco2250** [autoNumeric/autoNumeric#599] opened 2018-08-22 19:59 UTC
### Current behavior
When a input type=text has maxlength set, the component seems to ignore that attribute, letting the user to insert more digits than he or she is allowed to.

### Expected behavior
From my point of view, the component should not replace default browsers behavior and so it should limit the number of characters..

### Steps to reproduce the problem
1. Use autoNumeric version `4.2.15`
2. In the browser `<Chrome>`
3. On the `Windows` operating system
4. Then instantiate the autoNumeric object with the following options:
new AutoNumeric(domElement, { digitGroupSeparator: '', decimalPlaces: 0 });

### Link to live example
https://codepen.io/marco2250/pen/QVbppJ

**Comment by AlexandreBonneau** [comment] 2018-08-23 06:36
This is the intended behavior.
If the dev wants to limit the number of digits, it needs to set `maximumValue`, `minimumValue` and/or `decimalPlaces` accordingly.

I understand one would want to stay as close to the standard browser behavior, but having a `maxlength` attribute when you cannot know in advance how many digit separators and decimal character and/or suffix text you'll have is not handy.
Also, AutoNumeric on-the-fly formatting is hardly mimicking the default browser behavior anyway ;)

I'm not seeing AutoNumeric trying to respect the `maxlength` attribute without leading to numerous buggy side effects.

I'll close this for now. If you have a specific idea how we could include that 'feature', feel free to comment in this thread.

**Closed by AlexandreBonneau** 2018-08-23 06:36 UTC
