### ISSUE TITLE
When enter "," system converted it to ".", I don't want this functionality. can we ignore "," as we are ignoring alphabet. 

### ISSUE THREAD

**Issue by umeshverma** [autoNumeric/autoNumeric#530] opened 2017-11-08 09:49 UTC
### Expected behavior
<System should ignore "," as it is ignoring alphabet>

### Actual behavior
<System is showing "." when I press "," key>

### Steps to reproduce the problem
1. Please find all the configuration and option in live example.

### Link to live example (https://codepen.io/umesh-ithands/pen/xPRgmy?editors=1111))

Thanks

**Comment by AlexandreBonneau** [comment] 2017-11-08 10:26
This is a duplicate of issue #432.

**Closed by AlexandreBonneau** 2017-11-08 10:26 UTC
Labels: Duplicate
