### ISSUE TITLE
'Paste' operation does not work correctly in IE browser when comma exists

### ISSUE THREAD

**Issue by VoimiX** [autoNumeric/autoNumeric#517] opened 2017-10-20 09:21 UTC
### Expected behavior
After pasting `"39,23"` value it should become `"39.23"`

### Actual behavior
After pasting `"39,23"` it becomes `"3 923.00"`

### Steps to reproduce the problem
1. Using autoNumeric `4.0.3` , `4.1.0-beta.12`  and the browser `IE` version `11` on `Windows`,
2. I used the options
```js
  decimalCharacterAlternative: ',',    
     digitGroupSeparator: ' ',
     minimumValue: 0,
     modifyValueOnWheel: false,
```
3. Initialized my AutoNumeric object with the call
```js
 $("[data-money]").each(function(ndx, lmnt) {
   var n = new AutoNumeric(lmnt, { 
   	 decimalCharacterAlternative: ',',    
     digitGroupSeparator: ' ',
     minimumValue: 0,
     modifyValueOnWheel: false,
   });
 });
```
4. Paste value `"39,23"`
   It becomes  `"3 923.00"`

### Link to live example
https://jsfiddle.net/qm01xh6v/29/

**Comment by AlexandreBonneau** [comment] 2017-10-20 20:33
This issue is a duplicate of https://github.com/autoNumeric/autoNumeric/issues/424.
See the thread for more details about it.

**Closed by AlexandreBonneau** 2017-10-20 20:33 UTC
